### ISSUE TITLE
add `wp-env` end to end testing

### ISSUE THREAD

**Issue by petit-chat** [petit-chat/petit-filou#36]
workflow job:

```yaml
  wp-test:
    runs-on: ubuntu-latest
    steps:
      - uses: godaddy-wordpress/setup-wp-env@v1
      - run: |
          wp-env run cli "wp post generate --post_title='Hello World'"
          wp-env run cli "wp media import sample-image.jpg --post_id=1"
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build -r
      - run: ./target/release/pf http://localhost:8889

```
